name: Reusable

on:
  workflow_dispatch:

jobs:
  first:
    uses: konradpabjan-playground/reusable1/.github/workflows/first.yml@main
    secrets: inherit
  second:
    uses: konradpabjan-playground/reusable2/.github/workflows/second.yml@main
    secrets: inherit
