name: Reusable

on:
  workflow_dispatch:

jobs:
  first:
    uses: konradPabjan/reusable-workflow-test/.github/workflows/blank.yml@main
    secrets:
      MY_SECRET: ${{ secrets.MY_SECRET }}
  second:
    uses: konradpabjan/reusable-workflow-test/.github/workflows/blank.yml@main
    secrets:
      MY_SECRET: ${{ secrets.MY_SECRET }}
