name: Reusable

on:
  workflow_dispatch:

jobs:
  first:
    uses: konradpabjan-playground/reusable2/.github/workflows/second.yml@main
    secrets: inherit
  second:
    uses: konradPabjan-playground/reusable2/.github/workflows/third.yml@main
    secrets: 
      MY_SECRET3: ${{ secrets.MY_SECRET3 }}
